version: '3.8'
services:
  bq:
    image: gutils
    #command: [ "tail", "-f", "/dev/null" ]
    ports:
      - "2200:22"
    volumes:
      - ./service_account_key.json:/root/.config/gcloud/application_default_credentials.json
      - ./scripts:/home/scripts
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/root/.config/gcloud/application_default_credentials.json
      - mi_dataset=miDataset
      - mi_tabla=tablaEjemplo
      - ruta_esquema=./personas.json
      - ruta_ficheros_temporales_para_cargar=/home/examplecsv
